### ISSUE TITLE
Monster can't attack across inter-tile walls

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#248] opened 2021-04-01 03:06 UTC
Monsters currently can't attack across inter-tile walls, even when you are standing up.

**Comment by nsmryan** [comment] 2021-04-01 04:07
I believe the problem is in clear_path_up_to.
If the monster is 1 tile away from the player, move_next_to returns the start position. This makes clear_path return true, as there is no distance between the tiles.
The AI then believes it can attack the player, and tries to.

**Comment by nsmryan** [comment] 2021-04-02 12:29
This should be fixed. The check now looks separately for entities and a clear path on the map.

**Comment by nsmryan** [comment] 2021-04-08 04:01
The AI should be able to attack over intertile walls.
This requires checking for paths that are blocked only by intertile walls. This was done with the BlockedType::Fov check.

Now AI needs to generate an attack, not a move, so that they are not blocked.

**Comment by nsmryan** [comment] 2021-04-09 12:03
Added an attack variant to Action, and use this to attack a position. if the position then has an entity, it is attacked (any entity that can be attacked, even other golems right now).

**Comment by nsmryan** [comment] 2021-05-30 15:36
This does not currently work. Action has been removed, so the above solution will not work.

**Comment by nsmryan** [comment] 2021-05-30 15:58
I looked into this a bit, and I think we need to discuss attacking vs pushing. I found where the AI decides that they cannot attack, but I can't just make it an attack because then the player would also attack in that situation.
This made me think that I'm not sure when an entity attacks vs pushes vs moves. Under what conditions should each of these options be taken?
I could see some golems only push, while others attack. Perhaps entities need an "attack type" component so we can determine what to do in these situations. If so, pushing and non-attacking entities will just walk up to the wall in this case, while attacking ones will attack over the wall.

**Comment by nsmryan** [comment] 2021-06-01 03:27
resolve_ai_attack should generate an attack message, not a TryMove message- the AI has already determined for itself that it can attack and does not need to try a move which then generates an attack.
This will fix the monster attack over wall issue, but make sure that the conditions for attacking allow it.

The issue of attack types will be in a separate issue.

**Comment by nsmryan** [comment] 2021-06-02 02:47
The message should be TryAttack. This change in now on the develop branch.

**Closed by nsmryan** 2021-06-02 02:47 UTC
Labels: bug
