### ISSUE TITLE
Pushing column over doesn't make sound

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#153] opened 2020-08-03 05:09 UTC
[issue153.txt](https://github.com/nsmryan/RustRoguelike/files/5014003/issue153.txt)

**Comment by nsmryan** [comment] 2020-08-03 13:01
This is because we removed playing sounds for things you can see. There is a special case for sounds directly caused by the player.
Currently the "source" of the sound is the column. I think maybe we should make the source the player, but that wouldn't help for sounds that are caused by second order effects like the column hitting something.  

I'm not sure what else to do about this. I considered adding a check for sounds caused by enemies. The condition would be- any sound caused by an enemy that does not overlap with the player is not displayed, any other sound is displayed.
The problem is that a sound caused by something an enemy does would still be displayed, so something caused by something the enemy does.

I also considered showing any sound that overlaps with the player- this might be the best solution. We could filter out sounds from enemies that are in your FOV if want to reduce the visual noise, but all other sounds would be shown.

**Comment by MicroChasm** [comment] 2020-08-03 22:53
I think that the question is-- what sounds does the player need to know about in order to make good decisions? The player needs to know about monster movement when they are not visible in order to be aware of their movement, but it's not important what sounds the monster make from movement if the monster is in LOS. The player does want to know about side effects of monster actions, like knocking over a column, because it could cause other monsters to investigate. So in the end I think that there is only one type of sound that should be filtered out-- sound from monster movement when they are in LOS.

**Comment by nsmryan** [comment] 2020-08-06 02:40
Try it out, this should be fixed.

**Closed** 2020-08-15 23:07 UTC
Labels: Waiting Confirmation, bug
